### PR TITLE
[wip?] Add option for voice call member list to display persistently

### PR DESCRIPTION
**Pull request by iyu46**
image

image

perfectly serviceable in its current state but there's room for adding in icons and stuff when speaking, muted, or deafened, but I can't currently get the images to load in when testing D: if wanting to push, can just remove all references to the new images

but with upcoming savage + rl stuff unsure if i'll have capacity to investigate it more khljsdfkjds

### CODE REVIEW

**Comment by keysmashes** [comment]
i've not forgotten about this, apologies for the long wait – i will attempt to review this at some point this weekend

**Comment by keysmashes** [comment]
looks good to me! the images seem to nearly work, I'll get them fixed before pushing a release

do you know what license the image files are under? would you mind adding a note somewhere (the readme, a tooltip, the plugin manifest) to comply with the license terms?

**Comment by iyu46** [comment]
ah right sorry! the icons are under the apache license 2.0, and i think it's just including both the copyright notice and a note? i'm not entirely sure i parse the terms of (realistic) use of something under the apache license and what we have to do, because the copyright notice itself only refers to if you want to put your work under the apache license

image
https://www.apache.org/licenses/LICENSE-2.0.html

**Comment by iyu46** [comment]
okay they say attribution is fine so i'll add a note on that, i don't think we want to add the apache license since we're not putting the work under that license? doing a push rq

image
https://github.com/google/material-design-icons/tree/master

**Comment by keysmashes** [comment]
awesome, thank you!

**Pull request merged**
